### ISSUE TITLE
Upgrading to v6.0.0 returns n/a for every license in the license column

### ISSUE THREAD

**Issue by danielbellmas** [BePo65/license-report#100]
## Steps To Reproduce
- Run `license-report --output=csv` (license-report@6.0.0)

 The output is a  CSV that almost every license is equal to `n/a` instead of the correct license.
Happend to me only when upgrading to v6.0.0, going back to version 5.0.2 works great 👌🏻

**Comment by BePo65** [comment]
Can you give me at least an excerpt of the generated output?

Did you install the packages before running license-report? Starting with v6 we need an node_modules directory with the installed packages.

**Comment by danielbellmas** [comment]
Can't really show the output but Here is a "mock" csv (replaced the package names and git URLs with `packageName` and `packageUrl` respectively).
<img width="769" alt="Screen Shot 2022-07-26 at 8 56 06" src="https://user-images.githubusercontent.com/76179660/180933679-9dc34749-72d0-4f29-8dec-d48b86806429.png">


What do you mean by package**s**? I've `npm install license-report` and then ran a script that runs `license-report --output=csv` at the appropriate path.

Thanks.

**Comment by BePo65** [comment]
Just to test the configuration I would recommend:
1. create an empty directory
2. open a console with this new directory as working directory
3. run `npm init -y`
4. run `npm install got`
5. run `npx license-report --output=table`  
Yes it is `npx` and not `npm` 😄 
6. copy the output into this issue as a comment.

I hope that I can get more infos with this sample.

**Comment by danielbellmas** [comment]
<img width="1908" alt="Screen Shot 2022-07-26 at 21 18 41" src="https://user-images.githubusercontent.com/76179660/181081922-b6a61154-dd21-4c5d-88d2-3db147be4787.png">

In this example only the author in `n/a`, which is reasonable.

Maybe it's because I npm installed the latest version of `license-report`, and didn't just execute it with `npx`?

Thank you for the quick responses 🙏🏼

**Comment by BePo65** [comment]
This looks better, but the n/a for the author is strange. If I do this on my machine (windows10, node 16.15.1) I get the following list:

![License-report_issue100](https://user-images.githubusercontent.com/6582465/181164302-34838291-3e2b-43b5-be0a-9466efd8065d.jpg)

What OS and what node version do you use?

**Comment by danielbellmas** [comment]
The OS is macOS v12.4 and the node version is v16.15.1.

**Comment by BePo65** [comment]
I double checked the output on windows and ubuntu (I have no access to a mac machine) and all was like expected. The point is that some packages don't have an author field (which results in `n/a`).

**Comment by BePo65** [comment]
Solved by pr #106

**Comment by asclearuc** [comment]
Have the same issue:
```
$ npm install -g license-report@5.0.2
$ npx license-report --package=./src/package.json --output=json | jq -r ".[].licenseType"
Apache-2.0
MIT
MIT
MIT
MIT
$ npm install -g license-report@6.0.0
$ npx license-report --package=./src/package.json --output=json | jq -r ".[].licenseType"
n/a
n/a
n/a
n/a
n/a
```

**Comment by BePo65** [comment]
The difference is that we get the data from the package.json in the node_module folder. So it would be interesting, what is the license type in that files.

Besides: just do trace the effect down on my system, it would be great, if you could show the 'dependencies' and 'devDependencies' of the package under inspection.

**Comment by asclearuc** [comment]
I'm not quite proficient with Node.js (it is used by another tool, but I have to follow license info) - so if some addition info is needed - let me know.
 package.json:
```
{
  "name": "my-project-name",
  "description": "my-project-name",
  "version": "0.0.0",
  "main": "index.js",
  "license": "SEE LICENSE IN LICENSE",
  "scripts": {
    "lint": "eslint .",
    "lint-fix": "eslint --fix .",
    "clean": "rm -rf node_modules"
  },
  "devDependencies": {
    "eslint": "^7.12.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-plugin-import": "^2.22.1"
  },
  "dependencies": {
    "aws-sdk": "^2.1048.0",
    "pg": "^8.6.0"
  }
}
```
and output of `license-report@v5.0.2`:
```
[{
        "department": "kessler",
        "relatedTo": "stuff",
        "name": "aws-sdk",
        "licensePeriod": "perpetual",
        "material": "material",
        "licenseType": "Apache-2.0",
        "link": "git://github.com/aws/aws-sdk-js.git",
        "remoteVersion": "2.1187.0",
        "installedVersion": "no entry in packagelock.json",
        "definedVersion": "^2.1048.0",
        "author": "Amazon Web Services https://aws.amazon.com/"
    }, {
        "department": "kessler",
        "relatedTo": "stuff",
        "name": "pg",
        "licensePeriod": "perpetual",
        "material": "material",
        "licenseType": "MIT",
        "link": "git://github.com/brianc/node-postgres.git",
        "remoteVersion": "8.7.3",
        "installedVersion": "8.6.0",
        "definedVersion": "^8.6.0",
        "author": "Brian Carlson brian.m.carlson@gmail.com"
    }, {
        "department": "kessler",
        "relatedTo": "stuff",
        "name": "eslint",
        "licensePeriod": "perpetual",
        "material": "material",
        "licenseType": "MIT",
        "link": "git+https://github.com/eslint/eslint.git",
        "remoteVersion": "7.32.0",
        "installedVersion": "7.29.0",
        "definedVersion": "^7.12.0",
        "author": "Nicholas C. Zakas nicholas+npm@nczconsulting.com"
    }, {
        "department": "kessler",
        "relatedTo": "stuff",
        "name": "eslint-config-airbnb-base",
        "licensePeriod": "perpetual",
        "material": "material",
        "licenseType": "MIT",
        "link": "git+https://github.com/airbnb/javascript.git",
        "remoteVersion": "14.2.1",
        "installedVersion": "14.2.1",
        "definedVersion": "^14.2.0",
        "author": "Jake Teton-Landis https://twitter.com/@jitl"
    }, {
        "department": "kessler",
        "relatedTo": "stuff",
        "name": "eslint-plugin-import",
        "licensePeriod": "perpetual",
        "material": "material",
        "licenseType": "MIT",
        "link": "git+https://github.com/import-js/eslint-plugin-import.git",
        "remoteVersion": "2.26.0",
        "installedVersion": "2.23.4",
        "definedVersion": "^2.22.1",
        "author": "Ben Mosher me@benmosher.com"
    }
]
```

generated by `license-report@6.0.0`:
```
[{
        "department": "kessler",
        "relatedTo": "stuff",
        "name": "aws-sdk",
        "licensePeriod": "perpetual",
        "material": "material",
        "licenseType": "n/a",
        "link": "git://github.com/aws/aws-sdk-js.git",
        "remoteVersion": "2.1187.0",
        "installedVersion": "n/a",
        "definedVersion": "^2.1048.0",
        "author": "n/a"
    }, {
        "department": "kessler",
        "relatedTo": "stuff",
        "name": "pg",
        "licensePeriod": "perpetual",
        "material": "material",
        "licenseType": "n/a",
        "link": "git://github.com/brianc/node-postgres.git",
        "remoteVersion": "8.7.3",
        "installedVersion": "n/a",
        "definedVersion": "^8.6.0",
        "author": "n/a"
    }, {
        "department": "kessler",
        "relatedTo": "stuff",
        "name": "eslint",
        "licensePeriod": "perpetual",
        "material": "material",
        "licenseType": "n/a",
        "link": "git+https://github.com/eslint/eslint.git",
        "remoteVersion": "7.32.0",
        "installedVersion": "n/a",
        "definedVersion": "^7.12.0",
        "author": "n/a"
    }, {
        "department": "kessler",
        "relatedTo": "stuff",
        "name": "eslint-config-airbnb-base",
        "licensePeriod": "perpetual",
        "material": "material",
        "licenseType": "n/a",
        "link": "git+https://github.com/airbnb/javascript.git",
        "remoteVersion": "14.2.1",
        "installedVersion": "n/a",
        "definedVersion": "^14.2.0",
        "author": "n/a"
    }, {
        "department": "kessler",
        "relatedTo": "stuff",
        "name": "eslint-plugin-import",
        "licensePeriod": "perpetual",
        "material": "material",
        "licenseType": "n/a",
        "link": "git+https://github.com/import-js/eslint-plugin-import.git",
        "remoteVersion": "2.26.0",
        "installedVersion": "n/a",
        "definedVersion": "^2.22.1",
        "author": "n/a"
    }
]
```

So, you see that at least licenseType && author - disappear

**Comment by BePo65** [comment]
I tried your package.json in several combinations and everything ran as expected :-(

Here is a little overview about the sources for the different license-report fields:
| fieldname | column title | data source V5 | data source V6 |
|---|---|---|---|
| definedVersion | defined version | project package.json | project package.json |
| name | name | package package.json | package package.json |
| link | link | registry | registry |
| installedFrom | installed from | --- | registry |
| remoteVersion | remote version | registry | registry |
| installedVersion | installed version | project package-lock.json | node_modules |
| licenseType | license type | registry | node_modules |
| author | author | registry | node_modules |
| comment | comment | deprecated (registry, remoteVersion)) | deprecated (registry, remoteVersion) |
| department | department | config.js | config.js |
| relatedTo | related to | config.js | config.js |
| licensePeriod | license period | config.js | config.js |
| material | material / not material | config.js | config.js |

As you can see, all fields missing in your v6.0.0 output come from the node_modules directory.  
And that was a breaking change in v6: the **packages** of the project under inspection **must be installed**, before running license-report can generate a report.  
By dropping the package-lock.json as datasource, we made license-report usable for other package managers (i.e. pnpm and yarn).

Can it be that you have no node_modules in the project under inspection (i.e. did you run `npm i`)? For me it looks like this is not the case.

**Comment by asclearuc** [comment]
Tx you, it worked with `npm i`
