### ISSUE TITLE
Registry prop without latest slash throw an error

### ISSUE THREAD

**Issue by WuglyakBolgoink** [BePo65/license-report#101]
if I use `--registry=my.registryserver.com/some/path`, then I have an error because the result link for `bootstrap` will be so:
`my.registryserver.com/some/pathbootstrap`

but should be `my.registryserver.com/some/path/bootstrap`

it will be better to add an additional check for the last slash, and if not exists, then add it manually.

**Comment by BePo65** [comment]
Solved with pr #104
