### ISSUE TITLE
Markdown Output

### ISSUE THREAD

**Issue by mariusmuntean** [BePo65/license-report#115]
It would be useful if Markdown was added to the available outputs. 
The default table is already great, but if it were possible to have a Markdown table then the results could be rendered nicely without any post processing.

**Comment by BePo65** [comment]
Good idea. The default (internal) format is json. Can I motivate you to create a json-to-md-formatter, e.g. by using the [tablemark](https://www.npmjs.com/package/tablemark) package ?-)

**Comment by mariusmuntean** [comment]
I gave it a shot in #116

**Comment by BePo65** [comment]
Give me a few days for a deeper look - especially I am thinking about the configuration for the tablemark package.

**Comment by mariusmuntean** [comment]
Sure, take your time.
I though about exposing some of tablemark's features, e.g. aligning the field values in the table cell. Without clear requirements, I opted for the simplest implementation that works.
let me know which of tablemarks's features you think are a must here.

**Comment by mariusmuntean** [comment]
Did you get a chance to think about this?
