### ISSUE TITLE
Link field returning the git link instead of the homepage

### ISSUE THREAD

**Issue by Roshanalexander** [BePo65/license-report#125]
Is there any way to display the git homepage url instead of the git clone url in the report?

Right now, field=link returns git+https://github.com/axios/axios.git instead of returning the repo homepage url https://github.com/axios/axios.

![image](https://user-images.githubusercontent.com/6432696/223759048-25f4572d-d372-491b-bbdf-b43838831eb0.png)

**Comment by BePo65** [comment]
Technically it would be no problem to make the 'homepage' field as an **additional** optional field to license-report.
But we wanted to avoid an inflation of fields in license-report - in the end, we would take all fields from the package.json 😄 .

So I think it is time to think about adding new fields by configuration (i,e, by settings in the config file).

Give me a few days.

**Comment by Roshanalexander** [comment]
That'd be awesome. Thank you!

**Comment by BePo65** [comment]
fixed by pr #125.
