### ISSUE TITLE
Transitive Licenses

### ISSUE THREAD

**Issue by minecrawler** [BePo65/license-report#142]
It's great to get a report about direct licenses, however they are mostly already known to developers, since they add them manually. What's more interesting, for legal reasons, are transitive licenses. 

Is there a way to get them using this tool, or do you plan to add them?

**Comment by BePo65** [comment]
By 'transitive license' you mean the licenses of the dependencies of the direct dependencies.
To get the indirect licenses we need to recurse through all the licenses.

To keep license-report focused, I created a derived version with recursion: [license-report-recursive](https://www.npmjs.com/package/license-report-recursive) on npm with the repository on [github](https://github.com/bepo65/license-report-recursive/). Just give it a try.
