### ISSUE TITLE
How do I output the `repository.url` as a custom field?

### ISSUE THREAD

**Issue by alex-martinez** [BePo65/license-report#181]
When having a custom field, what's the syntax for getting using a field for a key that's nested in the package.json? For example, `repository.url`.

I tried `npx license-report --output=csv --fields=repository.url --repository.url.label="Repo" --repository.url.value="n/a"`

**Comment by BePo65** [comment]
I think that at the moment this is not possible.

In 'addLocalPackageData.js' line 65 we do a simple object reference
`element[fieldName] = packageJSONContent[fieldName];` and in your case ´fieldName´ would be `repository.url` and of course this will fail.

Could you be motivated to create a pr for this 😄 ?

**Comment by BePo65** [comment]
Solved by pr #194 - waiting for publishing project to npmjs by owner.

**Comment by BePo65** [comment]
published as 6.7.0
