### ISSUE TITLE
Release v6.6.1

### ISSUE THREAD

**Issue by jerone** [BePo65/license-report#192]
[NPM](https://www.npmjs.com/package/license-report?activeTab=versions) says the latest version is v6.5.0, but the [changelog](https://github.com/kessler/license-report/blob/HEAD/CHANGELOG.md) & [tags](https://github.com/kessler/license-report/tags) in this repo say v6.6.1 is the latest.

I know ownership changed, so maybe something went wrong pushing the new version...

**Comment by BePo65** [comment]
i was upgraded as a npm maintainer and publishe the latest release.
