### ISSUE TITLE
Sanitize field values for csv format

### ISSUE THREAD

**Issue by kessler** [BePo65/license-report#31]
currently when outputting to csv some values might break csv because they have the delimiter character in them

**Comment by BePo65** [comment]
do you have an example? I tried it with the project itself (`node ./index.js --output=csv`) and the output was fine.

But anyway: in case of problems you can change the delimiter anytime using the method described in the readme (see [different output](https://github.com/ironSource/license-report#different-outputs)).

**Comment by kessler** [comment]
The most common delimiter which is `,` appeared for me once in the `author` field, as a result there was an _extra_ column in that row. In my opinion it's always good to insure that protocols and formats are enforced... prevents a lot of nasty surprises

**Comment by BePo65** [comment]
Hm, that's right for sure, but csv is not a standardized format
We could surround all field values with quotes (or at least all values containing the separator) but then we would have to think about values containing quotes :-).
And I am not sure, if all tools that import csv will accept quoted strings.

An alternative would be changing the field value by replacing all delimiter characters by another character - but what to use here?

What application do you have in mind that will import the generated csv file?

**Comment by kessler** [comment]
All very valid points!

We can start by throwing an error or just printing a warning that a delimiter character appears in a value and then maybe provide flags to do something with it (like escaping etc...)

wdyt?

**Comment by BePo65** [comment]
good idea. Should I make a first draft of a solution as a pullrequest? Perhaps I find the time on the weekend?

**Comment by kessler** [comment]
That would be awesome.
