### ISSUE TITLE
Inconsistent behaviour under different output types

### ISSUE THREAD

**Issue by vishakvinod** [BePo65/license-report#36]
I am trying to repurpose the "relatedTo" column to display the current version of my application. But I am getting inconsistent behavious when the output is "html" and "table".
When I try to output the result as a table by running the following command
```sh 
license-report --output=table --package=package.json --relatedTo.label="Version" --relatedTo.value=1.0.3
```
I get the expected result as shown in the image
![output-table](https://user-images.githubusercontent.com/22879672/99273775-78d9d000-284f-11eb-9b47-1c9a5e9549c2.jpg)

But the story is not the same try to output as html. 
Using the following command 
```sh 
license-report --output=html --package=package.json --relatedTo.label="Version" --relatedTo.value=1.0.3 > dependencies.html
```
The column label dosent get updated as shown in the image below
![output-html](https://user-images.githubusercontent.com/22879672/99269463-5befcd80-284c-11eb-8e19-8c4aa07ad8da.jpg)

Which one of this is the expected behaviour ?

PS: In your README.md, there is a section on "customize a default value (only applicable for some fields)". Could you also list out which are those applicable fields.

**Comment by BePo65** [comment]
<..."customize a default value (only applicable for some fields)". Could you also list out which are those applicable fields>:
the fields are listed a little bit further down the ReadMe under the heading "Fields with data set in the configuration of license-report"

**Comment by BePo65** [comment]
it seems as if the "label" is only evaluated for the table output.
I think that even csv and html output should use the "labels".
For csv this seems to be quite easy, for html the properties must be renamed before being sent to tableify (I tried this in a little test project).
