### ISSUE TITLE
Wrong output type inside repo with zero dependencies

### ISSUE THREAD

**Issue by DmitriiKasnitskii** [BePo65/license-report#42]
After a command inside repo with zero dependencies you get a text "nothing to do" despite the type into the command such as "license-report --output=json" or any other. The type should be predictable and based onto type in command

**Comment by BePo65** [comment]
As far as I understand license-report doesn't return a json file if there are no dependencies. You are right, that's not really consistent :-)
Can you give me the example repo you used for this test e.g. on stackblitz?

**Comment by DmitriiKasnitskii** [comment]
I think that I didn't explain it clear enough. Sorry, my bad. The full and correct example in directory without any dependencies will be:
license-report --output=json > output.json 
For writing it to a file. 
And in this case you have a file with the following string "nothing to do". But it will be not in JSON format.

![image](https://user-images.githubusercontent.com/19331627/106306131-a939e380-626e-11eb-942d-d6d93290ece4.png)

**Comment by BePo65** [comment]
OK; I see.
So today license-report emits "nothing to do" if there are no packages - irrespective of the desired output format. But changing this behavior would be a breaking change (even if it would improve the consistency of the output).

Can you tell us what use case you have in mind (as projects without any dependency seem quite a rare case to me - but probably I am only not creative enough ;-)?

**Comment by DmitriiKasnitskii** [comment]
Maybe if it's a breaking change it doesn't worth it at all because this case can be easily caught by a simply code guard :-)

My case is a number of repos with CI/CD pipeline that collects licenses from all project's repos and then aggregates it into one big license file. There was an error with file format because an aggregate function expected a JSON file

**Comment by BePo65** [comment]
I agree with your arguments.

@kessler What do you think about changing this behavior? Technically its only deleting one line - I've tried it out.

**Comment by kessler** [comment]
I think it's a bad decision I made back then when it was just a quick fix project. I wouldn't even dignify it with the word design, it was more of an afterthought apparently :-)

The tool should indicate there's _nothing to do_, but it should do so in a proper manner according to the user's expectations. 

So yea, we should definitely change this... and I'm not afraid of breaking changes where they are due. We bump the major, communicate this in the readme and we should be ok. Besides anyone who uses `nothing to do` right now probably has some sort of a conditional to test it anyways.

Only question now is whether it should be a completely empty file or something else or both? 

Currently we have 4 output formats. For _json _it's easy to do: ```{  results: [] }``` or whatever but for _csv_ it can be just nothingness or just headers. Then we have the "beauty" formats, html and text table ofcourse.

I'm thinking each format should have it's own _nothing to do_ no results response, but maybe it should be an empty file for everyone, WDYT?

**Comment by BePo65** [comment]
I have tried out what happens. when we simply omit the line that emits the 'nothing to do'; what we get is:

- output=json => [] (an empty array) - that is IMHO consistent with the array of objects that we get if there are dependencies.
- output=html => an empty table (even no header - should have header?)
- output=csv => a file with only one linefeed as content (should be completely empty?) or with headers
- output=table => a file with only the headers (looks OK for me)

So I think `json` and `table` are OK;
the empty line for `csv` is consistent to the output in case of dependencies, as even then a LF is the last character;
the question is, if the `html` output should have a header; as `html` is mostly for showing the result to a user, I would prefer an empty table with  header (consistent to the `table` output (even if the implementation is more work).

**Comment by kessler** [comment]
Yea, html + csd need headers then we're good I think
