### ISSUE TITLE
include actual license text

### ISSUE THREAD

**Issue by capc0** [BePo65/license-report#48]
is it possible to inclide the actual license text as well?

**Comment by pluma** [comment]
As someone who went down this rabbit hole before: this is non-trivial as not all packages use well-formed license identifiers and not all packages include a LICENSE file and sometimes the LICENSE file, the license specified in the `package.json` and even license comments within the code may disagree.

**Comment by capc0** [comment]
understandable.

I see this package as a possible future replacement of https://github.com/davglass/license-checker which seems to be abondoned, but has this feature.

**Comment by McShelby** [comment]
Another solution could be the Github License API: https://docs.github.com/en/rest/reference/licenses#get-the-license-for-a-repository

**Comment by BePo65** [comment]
To keep 'license-report' focused I created a small 'add-on' tool called `license-downloader` that downloads all license file using the Github License API mentioned by @McShelby (thanks for this).

So after running
`npx license-report > ./license-report.json`
you can download all license files with
`npx license-downloader --source ./license-report.json --licDir ./license-files --download`

I hope it will solve the task.
