### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by ajsb85** [BePo65/license-report#6]

**Comment by ajsb85** [comment]
Bower is no longer maintained...

**Comment by kessler** [comment]
funny that you mention that, just ran into this an hour ago:

https://news.ycombinator.com/item?id=10892456

**Comment by kessler** [comment]
So shall we handle this or can I close this issue?

**Comment by ajsb85** [comment]
😄 Go ahead, long live Bower!
https://bower.io/blog/2016/using-bower-with-yarn/
