### ISSUE TITLE
Allow fetching license info from `peerDependencies` and `optionalDependencies`

### ISSUE THREAD

**Issue by pubmikeb** [BePo65/license-report#61]
`license-report` outputs all licenses from `dependencies` and `devDependencies`.

Please, add support of `peerDependencies`, `optionalDependencies`, and `bundledDependencies` as well.
I would like to be able to retrieve the license info for the packages from these three extra dependencies.

**Comment by BePo65** [comment]
Thanks for the idea to make license-report more complete.
I do understand the `peerDependencies` and the `optionalDependencies`.

But according to the documentation of npm, packages listed in `bundledDependencies` do not contain any version info and must be also part of `dependencies`. Do you have a real live example of `bundledDependencies`?

**Comment by pubmikeb** [comment]
You're right, I've added `bundledDependencies` just to cover all possible types of dependencies.
In fact, just adding `peerDependencies` and `optionalDependencies` makes sense.

**Comment by pubmikeb** [comment]
I had a _brief_ look into codebase, it looks like this change requires the following code:

```js
const peerDeps = packageJson.peerDependencies
const optDeps = packageJson.optionalDependencies

if (!config.only || config.only.indexOf('prod') > -1) {
	addPackagesToIndex(deps, depsIndex, exclusions)
}

if (!config.only || config.only.indexOf('dev') > -1) {
	if (peerDeps) {
		addPackagesToIndex(peerDeps, depsIndex, exclusions)
	}
	if (optDeps) {
		addPackagesToIndex(optDeps, depsIndex, exclusions)
	}
	addPackagesToIndex(devDeps, depsIndex, exclusions)
}
```

If my assumption is right, should I prepare a PR?

Of course, extra flag might be added to cover a need to include extra dependencies.

**Comment by BePo65** [comment]
A PR would be welcome. But watch out: peerDeps and optDeps must not exist in package.json. Please add a test for a package.json without peerDependencies or optionalDependencies too.

**Comment by pubmikeb** [comment]
Done.
The PR is ready, please check if it's OK and suits the entire codebase style.

**Comment by BePo65** [comment]
Is part of the next release (based on pr #65).
