### ISSUE TITLE
Allow specifying running flags/args/params in JSON-config file

### ISSUE THREAD

**Issue by pubmikeb** [BePo65/license-report#62]
`license-report` supports multiple flags/args/params, e.g. `--only`, `--package`, `--output` etc.

It would be great to consolidate all such configurations in one single JSON (e.g. `license-report-config.json`) and apply it with `--config`.

Currently, part of configurations can be done in JSON and part as flags/args/params only.
I would like to have all configurations in one single place.

**Comment by BePo65** [comment]
> Currently, part of configurations can be done in JSON and part as flags/args/params only.

That feature already exists, but the documentation is not clear enough. The example in the readme mixes a custom config file and a command line option:
```
# set options with command line options and config file
license-report --output=csv --config license-report-config.json
```

But you can put any option into a config file and use it like this:
```
license-report --config license-report-config.json
```

Options that are not part of the custom config file are taken from the command line or the default configuration.

**Comment by pubmikeb** [comment]
Thanks,
`"output"="json"` in JSON works.
But is there an option to specify in JSON file an output file, e.g. `> ./src/license-report.json`?

**Comment by pubmikeb** [comment]
> _That feature already exists, but the documentation is not clear enough._

It would be great to arrange a JSON schema template for `license-report` via the [`schemastore`](https://github.com/SchemaStore/schemastore) project.

**Comment by BePo65** [comment]
> It would be great to arrange a JSON schema template for license-report via the schemastore project.

Feel free to do it yourself. The parameters in `lib/config.js` are all commented and the possibility of using a config file as command line parameter is a function of the package `rc` used to access the command line parameters.

**Comment by BePo65** [comment]
> But is there an option to specify in JSON file an output file, e.g. > ./src/license-report.json?

No, license-report uses the flexibility of using stdout by design. This way you can use redirecting, piping and more.

**Comment by pubmikeb** [comment]
> Feel free to do it yourself. The parameters in `lib/config.js` are all commented and the possibility of using a config file as command line parameter is a function of the package `rc` used to access the command line parameters.

OK, I'll check what can be done.

**Comment by pubmikeb** [comment]
> > It would be great to arrange a JSON schema template for license-report via the schemastore project.
> 
> Feel free to do it yourself. The parameters in `lib/config.js` are all commented and the possibility of using a config file as command line parameter is a function of the package `rc` used to access the command line parameters.

I've prepared an initial version of the schema based on `lib/config.js`.
However, the build https://github.com/SchemaStore/schemastore/pull/1713 is failed although the schema itself is valid.

Please, have a look, perhaps I forgot something critical.

Thanks.

**Comment by BePo65** [comment]
I have never used schema.org - so give me some time to familiarize with the topic. It is always good to get new inspirations - perhaps I can use it in my daily work too ....

**Comment by pubmikeb** [comment]
It's a great resource containing and maintaining schemas for tones of different projects!

**Comment by pubmikeb** [comment]
The new consolidated PR https://github.com/SchemaStore/schemastore/pull/1716 with the schema is ready to be deployed.

Inside:
* schema
* test cases for basic and full schema
* schema meta-description in `catalog.json`

Notes:
* it contains full specification according to `config.js`
* auto-suggestion should work
* fixed typo in `escapeCsvFields` property name (`Filelds` vs. `Fields`)

Hopefully, this schema will be deployed soon and we could enjoy `license-report` with JSON-schema validation!

**Comment by BePo65** [comment]
Do you have any idea how to use it e.g. on vscode?

**Comment by pubmikeb** [comment]
> Do you have any idea how to use it e.g. on vscode?

VS Code should have an appropriate JSON configurations section in `settings.json`.
I would check:

```js
// When enabled, JSON schemas can be fetched from http and https locations.
"json.schemaDownload.enable": true,

// Associate schemas to JSON files in the current project.
"json.schemas": [],
```

In `json.schemas` array a schema URL should be stored, e.g.:

```js
"json.schemas": [
	"https://json.schemastore.org/license-report-config.json"
]
```

Reference: https://code.visualstudio.com/docs/getstarted/settings

**Comment by pubmikeb** [comment]
> > It would be great to arrange a JSON schema template for license-report via the schemastore project.
> 
> Feel free to do it yourself. The parameters in `lib/config.js` are all commented and the possibility of using a config file as command line parameter is a function of the package `rc` used to access the command line parameters.

Done! The schema is available: https://json.schemastore.org/license-report-config.json

**Comment by pubmikeb** [comment]
The schema is published.
The initial question is resolved.
The ticket is closed.
