### ISSUE TITLE
Author  field in babel is not coming trough anymore - V5.0.0

### ISSUE THREAD

**Issue by BePo65** [BePo65/license-report#68]
@BePo65 thank you. I notice that for babel author for some reason is not coming trough anymore... Have there been any change about this?

_Originally posted by @gabrielmicko in https://github.com/ironSource/license-report/issues/65#issuecomment-1043037370_

**Comment by BePo65** [comment]
@gabrielmicko can you please give me the corresponding dependency lines from your package.json?

**Comment by BePo65** [comment]
OK, I see the error and will track it down.

**Comment by BePo65** [comment]
Fixed with pr #68 and merged into master - waiting for new release (coming soon)

**Comment by BePo65** [comment]
new release (v5.0.1) is available.

**Comment by gabrielmicko** [comment]
Thank you, I will validate it and let you know.
