### ISSUE TITLE
Response Code 404 (Not Found) with local dependencies

### ISSUE THREAD

**Issue by thisisevanfox** [BePo65/license-report#85]
Hello all,

### NO PROBLEM WITH NODE, SEE UPDATE BELOW

I have recently installed Node version 14.19.2 in my WSL. Since upgrading to this version, I can no longer create a licence report because the command returns a 404 Not Found Error.

In another WSL instance with Node version 14.18.2, the creation of the report works perfectly. I have attached 2 screenshots with debug logging.

Can you please take a look at the problem? Downgrading my WSL instance to a version <14.19 is unfortunately not an option.

Many thanks and kind regards
Johannes

Output on Node 14.19.2:
![license_14 19 2](https://user-images.githubusercontent.com/43059689/171012208-1e86a3a9-e75a-4d61-bfe2-c72a51d40b8a.png)

Output on Node 14.18.2:
![license_14 18 2](https://user-images.githubusercontent.com/43059689/171012214-04569060-5a30-42f1-b1b6-649b09ab0aae.png)

### UPDATE
Issue has nothing to do with Node.

I found the problem. I have a local dependency in my package.json file:
`...
"local-dep": "file:ext/local-dep-2.13.6.tgz",
...`

When I remove this dependency the generation of the license report works perfectly.

I also tried it with a colleague in his WSL, who was still using an older version of licence-report. The generation worked perfectly for him. 

The output of the generated license-report with the local dependency was like this - which was OK for us:
`local-dep,n/a,n/a,n/a`

After updating to the current version of license-report, he also got the "404 Not Found" error.

The problem has nothing to do with the Node version. The problem seems to be that license-report in the new version can no longer handle local dependencies. Unfortunately, I had installed different versions of license-report on my WSL instances and therefore immediately suspected that it was due to the Node version.

**Comment by DmitryOlkhovoi** [comment]
I have the same issue. Can we just skip the 404 package?

**Comment by BePo65** [comment]
I tried to reproduce the issue, but without success.
My configuration:
OS:                 Windows 10 Pro 21H2
Patch Level:    Latests patches installed
Description:    Ubuntu 20.04.4 LTS
Release-Nr:     4.4.0-19041-Microsoft

I ran 'license-report' via `npx` as I did not install any package.
Here are the results of my test (I reduced the prompt to '>>>' to improve readability:

```
>>>$ export DEBUG=license-report*
>>>$ npx license-report --only=prod
npx: installed 47 in 6.353s
  license-report loading /home/entwicklung/license-report-issues/085/test-project/package.json +0ms
  license-report loading /home/entwicklung/license-report-issues/085/test-project/package-lock.json +6ms
Warning: the file '/home/entwicklung/license-report-issues/085/test-project/package-lock.json' is required to get installed versions of packages
  license-report:getPackageJson getPackageJson - REQUEST https://registry.npmjs.org/@kessler/tableify +0ms
  license-report:getPackageJson getPackageJson - REQUEST https://registry.npmjs.org/debug +4ms
  license-report:getPackageJson getPackageJson - REQUEST https://registry.npmjs.org/eol +1ms
  license-report:getPackageJson getPackageJson - REQUEST https://registry.npmjs.org/got +1ms
  license-report:getPackageJson getPackageJson - REQUEST https://registry.npmjs.org/rc +0ms
  license-report:getPackageJson getPackageJson - REQUEST https://registry.npmjs.org/semver +1ms
  license-report:getPackageJson getPackageJson - REQUEST https://registry.npmjs.org/text-table +1ms
  license-report:getPackageJson getPackageJson - REQUEST https://registry.npmjs.org/visit-values +0ms
[{"department":"kessler","relatedTo":"stuff","name":"@kessler/tableify","licensePeriod":"perpetual","material":"material","licenseType":"MIT","link":"git+https://github.com/kessler/node-tableify.git","remoteVersion":"1.0.2","installedVersion":"1.0.2","definedVersion":"^1.0.2","author":"Dan VerWeire, Yaniv Kessler"},{"department":"kessler","relatedTo":"stuff","name":"debug","licensePeriod":"perpetual","material":"material","licenseType":"MIT","link":"git://github.com/debug-js/debug.git","remoteVersion":"4.3.4","installedVersion":"4.3.4","definedVersion":"^4.3.4","author":"Josh Junon josh.junon@protonmail.com"},{"department":"kessler","relatedTo":"stuff","name":"eol","licensePeriod":"perpetual","material":"material","licenseType":"MIT","link":"git+https://github.com/ryanve/eol.git","remoteVersion":"0.9.1","installedVersion":"0.9.1","definedVersion":"^0.9.1","author":"Ryan Van Etten"},{"department":"kessler","relatedTo":"stuff","name":"got","licensePeriod":"perpetual","material":"material","licenseType":"MIT","link":"git+https://github.com/sindresorhus/got.git","remoteVersion":"11.8.5","installedVersion":"11.8.3","definedVersion":"^11.8.3","author":""},{"department":"kessler","relatedTo":"stuff","name":"rc","licensePeriod":"perpetual","material":"material","licenseType":"(BSD-2-Clause OR MIT OR Apache-2.0)","link":"git+https://github.com/dominictarr/rc.git","remoteVersion":"1.2.8","installedVersion":"1.2.8","definedVersion":"^1.2.8","author":"Dominic Tarr dominic.tarr@gmail.com dominictarr.com"},{"department":"kessler","relatedTo":"stuff","name":"semver","licensePeriod":"perpetual","material":"material","licenseType":"ISC","link":"git+https://github.com/npm/node-semver.git","remoteVersion":"7.3.7","installedVersion":"7.3.7","definedVersion":"^7.3.7","author":"GitHub Inc."},{"department":"kessler","relatedTo":"stuff","name":"text-table","licensePeriod":"perpetual","material":"material","licenseType":"MIT","link":"git://github.com/substack/text-table.git","remoteVersion":"0.2.0","installedVersion":"0.2.0","definedVersion":"^0.2.0","author":"James Halliday mail@substack.net http://substack.net"},{"department":"kessler","relatedTo":"stuff","name":"visit-values","licensePeriod":"perpetual","material":"material","licenseType":"MIT","link":"https://github.com/kessler/node-visit-values","remoteVersion":"2.0.0","installedVersion":"2.0.0","definedVersion":"^2.0.0","author":"Yaniv Kessler"}]
>>>$ node --version
v14.19.2
```

So can you see any differences on running the tests compared  to your way?

**Comment by thisisevanfox** [comment]
> So can you see any differences on running the tests compared to your way?

The only difference is that I am using Debian 10.

**Comment by BePo65** [comment]
OK, let's see, if I can try it on debian too.

But looking at the screenshots, it looks to me as so some package cannot be found on npmjs. Could you get me a package.json (I only need the dependencies and the devDependencies)?

**Comment by thisisevanfox** [comment]
I found the problem. I have a local dependency in my package.json file:
`...
"local-dep": "file:ext/local-dep-2.13.6.tgz",
...`

When I remove this dependency the generation of the license report works perfectly.

I also tried it with a colleague in his WSL, who was still using an older version of licence-report. The generation worked perfectly for him. 

The output of the generated license-report with the local dependency was like this - which was OK for us:
`local-dep,n/a,n/a,n/a`

After updating to the current version of license-report, he also got the "404 Not Found" error.

The problem has nothing to do with the Node version. The problem seems to be that license-report in the new version can no longer handle local dependencies. Unfortunately, I had installed different versions of license-report on my WSL instances and therefore immediately suspected that it was due to the Node version.

Can you confirm this? Then I would adjust the description and the title of the issue.

**Comment by BePo65** [comment]
to be honest: I never tested with local dependencies :-) Should have done that and will do that at once.

In one of the latest releases we changed to `got` as a replacement for the outdated `request`. So 'got' may handle `file:` sources other than 'request'.

I will fix this the next days.

**Comment by DmitryOlkhovoi** [comment]
Is it possible to not fail with 404?

**Comment by BePo65** [comment]
That's the minimum requirement - I just didn't expect that there are "invalid" uris in the package-lock.json as I did not think about local dependencies - my fault.

So Step 1 is to catch errors and step 2 is to evaluate local dependencies.

But give me some days - I do not have the time for that the next few hours 😄

**Comment by BePo65** [comment]
Solved by pr #87

**Comment by detaybey** [comment]
When will 5.1.0 we available on npm?

**Comment by BePo65** [comment]
I hope that it is done this evening.

**Comment by thisisevanfox** [comment]
Hi @BePo65, 

can you please look into this again? The latest version on npm is still 5.0.2. Thank you. 

Kind regards
Johannes
