### ISSUE TITLE
Is it possible to output into file using configuration?

### ISSUE THREAD

**Issue by DmitryOlkhovoi** [BePo65/license-report#88]
I did output with linux command `>` but it wont work on windows. Is it possible to configure this tool to output into file by default?

**Comment by DmitryOlkhovoi** [comment]
ok, `>` works on windows, but probably it will be good to have output to file :) Thanks

**Comment by BePo65** [comment]
I think that outputting to a file will require a few more configuration properties and in the end you get a long version of `>` (something like `--target=c:\temp\licenses.json`).

IMHO it is not worth the effort :disappointed:
